import urllib.request

# Admin token generated by create_admin.py
token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4NjcyOTg0OSwianRpIjoiYzg0ZjIxNjktNjYwOS00N2QyLWIzOTUtM2EwMDI5NmY0YTVjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluQGV4YW1wbGUuY29tIiwibmJmIjoxNzg2NzI5ODQ5LCJjc3JmIjoiYTQxNzE2OTgtZTI1My00MGZiLTg4NWQtYTZhMzkzYjBmODE0IiwiZXhwIjoxNzg2NzMwNzQ5fQ.lThwxAcsmOkpOmLQyjBtsfTWF9tW24Mibjxz8-lGeqA'

url = 'http://127.0.0.1:5000/admin/dashboard'
req = urllib.request.Request(url, headers={'Authorization': f'Bearer {token}'})
with urllib.request.urlopen(req) as res:
    body = res.read().decode('utf-8')
    print(res.status)
    print(body[:400])
