"""add predicted_gpa to performance

Revision ID: 18454ffe753e
Revises: 582791aa6556
Create Date: 2026-05-01 21:30:36.280246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18454ffe753e'
down_revision = '582791aa6556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_gpa', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performances', schema=None) as batch_op:
        batch_op.drop_column('predicted_gpa')

    # ### end Alembic commands ###
