"""align models with survey ingestion

Revision ID: 246c14ae7d7a
Revises: 3ef6af694df4
Create Date: 2026-04-22 17:16:13.227018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c14ae7d7a'
down_revision = '3ef6af694df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
